version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - APP_ENV=dev

###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.9.4}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-ChangeMe}
      MARIADB_USER: ${MARIADB_USER:-symfony}
    volumes:
      - db-data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  adminer:
    image: dehy/adminer

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###